lib/rankings_web/router.ex
defmodule RankingsWeb.Router do
  use RankingsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RankingsWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RankingsWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/runners", RunnerController, only:  [:index, :show, :edit]
    resources "/teams", TeamController, only: [:index, :show]
    resources "/races", RaceController,  only: [:index, :show]
    resources "/raceinstances", RaceInstanceController,  only: [:index, :show]
    resources "/results", ResultController,  only: [:index, :show]
    resources "/edges", EdgeController, only: [:index, :show]
    resources "/about", AboutController, only: [:index]
    # resources "/compare", CompareController, only: [:index, :show]
    resources "/virtual", VirtualController, only: [:index]

    get "/compare", CompareController, :index
    post "/compare", CompareController, :index
    get "/compare/:id1", CompareController, :first_runner
    post "/compare/:id1", CompareController, :first_runner
    get "/compare/:id1/:id2", CompareController, :show


		get "/search", SearchController, :index
		post "/search", SearchController, :index

end

  # Other scopes may use custom stacks.
  # scope "/api", RankingsWeb do
  #   pipe_through :api
  # end
end

lib/rankings_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Cross Country Rankings" %></h1>
  <p>A site for the comparison of NIRCA cross country performances.</p>
</section>

<section>
  <h3><%=link "Teams:", to: Routes.team_path(@conn, :index) %> <%= @teams %>
  <h3><%=link "Runners:", to: Routes.runner_path(@conn, :index) %> <%= @runners %>
  <h3><%=link "Races:", to: Routes.race_path(@conn, :index) %> <%= @races %>
  <h3><%=link "Results:", to: Routes.result_path(@conn, :index) %> <%= @results %>
  <h3><%=link "Race Instances:", to: Routes.race_instance_path(@conn, :index) %> <%= @instances %>
</section>

<div>
  <table class="main-page-top-25">
    <tr>
      <td>Name</td>
      <td>Rating</td>
      <td>Race</td>
    </tr>
    <%= for result <- @mens do %>
      <tr>
        <td><%= link result.runner.first_name <> " " <> result.runner.last_name, to: Routes.runner_path(@conn, :show, result.runner.id) %></td>
        <td><%= Float.round(result.rating, 2) %></td>
        <td><%= link result.race_instance.race.name, to: Routes.race_path(@conn, :show, result.race_instance.race.id)%></td>
      </tr>
    <% end %>
  </table>
  <table class="gap-table">
  </table>
  <table class="main-page-top-25" >
    <tr>
      <td>Name</td>
      <td>Rating</td>
      <td>Race</td>
    </tr>
    <%= for result <- @womens do %>
      <tr>
        <td><%= link result.runner.first_name <> " " <> result.runner.last_name, to: Routes.runner_path(@conn, :show, result.runner.id) %></td>
        <td><%= Float.round(result.rating, 2) %></td>
        <td><%= link result.race_instance.race.name, to: Routes.race_path(@conn, :show, result.race_instance.race.id)%></td>
      </tr>
    <% end %>
  </table>
</div>


<section class="row">
  <%# <article class="column"> %>
    <%# <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul> %>
  <%# </article> %>
  <article class="column">
    <%# <h2>Help</h2> %>
    <ul>
      <%# <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li> %>
      <li>
        <a href="https://twitter.com/seankane942">Twitter @cc-rankings</a>
      </li>
      <li>
        <a href="/about">Read more about how ratings are calculated</a>
      </li>
      <li>
        <a href="https://www.letsrun.com/news/2006/09/wejo-speaks-why-i-sucked-in-college/">One of my favorite training articles</a>
      </li>
    </ul>
  </article>
</section>