lib/rankings_web/router.ex
defmodule RankingsWeb.Router do
  use RankingsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RankingsWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RankingsWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/runners", RunnerController, only:  [:index, :show, :edit]
    resources "/teams", TeamController, only: [:index, :show]
    resources "/races", RaceController,  only: [:index, :show]
    resources "/raceinstances", RaceInstanceController,  only: [:index, :show]
    resources "/results", ResultController,  only: [:index, :show]
    resources "/edges", EdgeController, only: [:index, :show]
    resources "/about", AboutController, only: [:index]
    # resources "/compare", CompareController, only: [:index, :show]
    resources "/virtual", VirtualController, only: [:index]

    get "/compare", CompareController, :index
    post "/compare", CompareController, :index
    get "/compare/:id1", CompareController, :first_runner
    post "/compare/:id1", CompareController, :first_runner
    get "/compare/:id1/:id2", CompareController, :show


		get "/search", SearchController, :index
		post "/search", SearchController, :index

end

  # Other scopes may use custom stacks.
  # scope "/api", RankingsWeb do
  #   pipe_through :api
  # end
end

lib/rankings_web/controllers/compare_controller.ex
defmodule RankingsWeb.CompareController do
  use RankingsWeb, :controller
  import Logger

  alias Rankings.{Runner, Repo}

  def index(conn, params) do
    query = Runner.list_runners(params)

    id1 = get_in(params, ["id1"])
    id2 = get_in(params, ["id2"])

    runner1 = find_runner(id1)
    runner2 = find_runner(id2)

    render(conn, "index.html", runners: query, id1: id1, id2: id2, runner1: runner1, runner2: runner2)
  end

  def first_runner(conn, params) do #%{"id1" => id1}) do
    IO.puts "def"

    query = Runner.list_runners(params)
    id1 = get_in(params, ["id1"])
    runner1 = find_runner(id1)

    render(conn, "second.html", runner1: runner1, runners: query)
  end

  def second_search(conn, params) do #%{"id1" => id1}) do
    IO.puts "second"

    query = Runner.list_runners(params)
    id1 = get_in(params, ["id1"])
    runner1 = find_runner(id1)
    IO.puts query

    render(conn, "second.html", runner1: runner1, runners: nil)
  end

  def show(conn, params) do
    IO.puts "SHOW"
    id1 = get_in(params, ["id1"])
    id2 = get_in(params, ["id2"])

    runner1 = Runner.get_runner(id1) |> Repo.preload(:team)
    runner2 = Runner.get_runner(id2) |> Repo.preload(:team)

    results1 = Runner.get_athlete_results(id1)
    results2 = Runner.get_athlete_results(id2)

    render(conn, "show.html", runner1: runner1, runner2: runner2, results1: results1, results2: results2)
  end

  def find_runner(id) do
    if id == nil do
      nil
    else
      Runner.get_runner(id) |> Repo.preload(:team)
    end
  end

end

lib/rankings_web/views/compare_view.ex
defmodule RankingsWeb.CompareView do
  use RankingsWeb, :view

end

lib/rankings_web/templates/compare/index.html.eex
<h1>Compare two runners</h1>

<p>For now only comparison between two runners supported. Stay tuned for more comparisons in the future</p>

<%= if @id1 != nil do %>
  <table>
    <tr>
      <td>Runner 1: </td>
      <td><%= @runner1.first_name <> " " <> @runner1.last_name  %></td>
      <td><%= @runner1.year %>
      <td><%= @runner1.team.name %>
    </tr>
  </table>
<% end %>

<h2>Search for Runner</h2>
<%= form_for @conn, Routes.compare_path(@conn, :index), [method: :get], fn f -> %>
  <div>
    <%= search_input f, :first, placeholder: "First Name" %>
  </div>
  <div>
    <%= search_input f, :last, placeholder: "Last Name" %>
  </div>
  <%= submit "Search", to: Routes.compare_path(@conn, :index) %>
<% end %>

<h2>Results</h2>
<%= if @runners != nil do %>
  <table>
    <tr>
      <td>Name</td>
      <td>Year</td>
      <td>Team</td>
      <td>Select</td>
    </tr>
    <%= if length(@runners) != 0 do %>
      <%= form_for @conn, Routes.compare_path(@conn, :index), [method: :get], fn f -> %>
        <%= for r <- @runners do %>
        <tr>
          <td><%= r.first_name <> " " <> r.last_name %></td>
          <td><%= r.year %></td>
          <td><%= r.team.name %></td>
          <td><%= submit "Select", to: Routes.compare_path(@conn, :first_runner, r.id) %>
          <%= if @id1 == nil do %>
          <td><%= radio_button f, :id1, r.id, name: "id1" %></td>
          <% else %>
          <td><%= radio_button f, :id2, r.id, name: "id2" %></td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
    <% end  %>
  </table>
<% end %>

lib/rankings_web/templates/compare/second.html.eex
<h1>Compare two runners</h1>

<p>For now only comparison between two runners supported. Stay tuned for more comparisons in the future</p>

<%= if @runner1 != nil do %>
  <table>
    <tr>
      <td>Runner 1: </td>
      <td><%= @runner1.first_name <> " " <> @runner1.last_name  %></td>
      <td><%= @runner1.year %>
      <td><%= @runner1.team.name %>
    </tr>
  </table>
<% end %>

<%= if @runner1 != nil do %>
  <h2>Search for Runner</h2>
  <%= form_for @conn, Routes.compare_path(@conn, :first_runner, @runner1.id), [method: :get], fn f -> %>

    <div>
      <%= search_input f, :first, placeholder: "First Name" %>
    </div>
    <div>
      <%= search_input f, :last, placeholder: "Last Name" %>
    </div>
    <%= submit "Search", to: Routes.compare_path(@conn, :first_runner, @runner1.id) %>
  <% end %>
<% end %>

<h2>Results</h2>
<%= if @runners != nil do %>
  <table>
    <tr>
      <td>Name</td>
      <td>Year</td>
      <td>Team</td>
      <td>Select</td>
    </tr>
    <%= if length(@runners) != 0 do %>
        <%= for r <- @runners do %>
        <%= form_for @conn, Routes.compare_path(@conn, :show, @runner1.id, r.id), [method: :get], fn f -> %>
        <tr>
          <td><%= r.first_name <> " " <> r.last_name %></td>
          <td><%= r.year %></td>
          <td><%= r.team.name %></td>
          <td><%= submit "Select", to: Routes.compare_path(@conn, :show, @runner1.id, r.id) %></td>
        </tr>
        <% end %>
      <% end %>
    <% end  %>
  </table>
<% end %>

lib/rankings_web/templates/compare/show.html.eex
<h1>Comparison</h1>

<%= if @runner1 != nil do %>
<table>
  <p>Runner Details</p>
  <tr>
    <td><%= @runner1.first_name <> " " <> @runner1.last_name %></td>
    <td><%= @runner1.team.name %></td>
    <td><%= @runner1.year %></td>
    <td><%= @runner1.speed_rating %>
  </tr>
</table>
<table>
  <%= for result <- @results1 do %>
    <tr>
      <td><%= result.date %></td>
      <td><%= result.race_instance.race.name %>
      <td><%= result.distance %>
      <td><%= result.time %></td>
      <td><%= result.scaled_time %>
      <td><%= result.rating %>
    </tr>
  <% end %>
</table>
<% end %>

<%= if @runner2 != nil do %>
<table>
  <p>Runner Details</p>
  <tr>
    <td><%= @runner2.first_name <> " " <> @runner2.last_name %></td>
    <td><%= @runner2.team.name %></td>
    <td><%= @runner2.year %></td>
    <td><%= @runner2.speed_rating %>
  </tr>
</table>
<table>
  <%= for result <- @results2 do %>
    <tr>
      <td><%= result.date %></td>
      <td><%= result.race_instance.race.name %>
      <td><%= result.distance %>
      <td><%= result.time %></td>
      <td><%= result.scaled_time %>
      <td><%= result.rating %>
    </tr>
  <% end %>
</table>
<% end %>