lib/rankings_web/router.ex
defmodule RankingsWeb.Router do
  use RankingsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RankingsWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RankingsWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/runners", RunnerController, only:  [:index, :show, :edit]
    resources "/teams", TeamController, only: [:index, :show]
    resources "/races", RaceController,  only: [:index, :show]
    resources "/raceinstances", RaceInstanceController,  only: [:index, :show]
    resources "/results", ResultController,  only: [:index, :show]
    resources "/edges", EdgeController, only: [:index, :show]
    resources "/about", AboutController, only: [:index]
    # resources "/compare", CompareController, only: [:index, :show]
    resources "/virtual", VirtualController, only: [:index]

    get "/compare", CompareController, :index
    post "/compare", CompareController, :index
    get "/compare/:id1", CompareController, :first_runner
    post "/compare/:id1", CompareController, :first_runner
    get "/compare/:id1/:id2", CompareController, :show


		get "/search", SearchController, :index
		post "/search", SearchController, :index

end

  # Other scopes may use custom stacks.
  # scope "/api", RankingsWeb do
  #   pipe_through :api
  # end
end

lib/rankings/edge.ex
defmodule Rankings.Edge do
  use Ecto.Schema
  import Ecto.{Query}

  alias Rankings.{Repo, Edge, RaceInstance}

  schema "edges" do
    belongs_to :from_race, RaceInstance
    belongs_to :to_race, RaceInstance
    field :difference, :float
    field :gender, :string
    belongs_to :runner, Rankings.Runner

    timestamps()
  end

  def get_runner_edges(id) do
    q = from(e in Rankings.Edge, where: e.runner_id == ^id, order_by: [:difference])
    Repo.all(q)
    |> Repo.preload([{:from_race, :race}, {:to_race, :race}])
  end

  def slowest_n_edges(n) do
    q = from(e in Edge, limit: ^n, order_by: [desc: :difference])
    Repo.all(q)
    |> Repo.preload([:runner])
  end

  def fastest_n_edges(n) do
    q = from(e in Edge, limit: ^n, order_by: [:difference])
    Repo.all(q)
    |> Repo.preload([:runner])
  end

  def get_edge(id) do
    Repo.get(Edge, id)
    |> Repo.preload([:runner, {:from_race, :race}, {:to_race, :race}])
  end

  def get_edges(from_id, to_id) do
    q = from e in Edge, where: e.from_race_id == ^from_id and e.to_race_id == ^to_id, order_by: [desc: :difference]
    Repo.all(q)
    |> Repo.preload([:runner, {:from_race, :race}, {:to_race, :race}])
  end

  def count_edges(from_id, to_id) do
    q = from e in Edge, select: count(),  where: e.from_race_id == ^from_id and e.to_race_id == ^to_id
    Repo.one(q)
  end

  def get_avg(from_id, to_id) do
    q = from e in Edge, where: e.from_race_id == ^from_id and e.to_race_id == ^to_id, select: avg(e.difference)
    Repo.one(q)
  end

  def get_std_dev(from_id, to_id) do
    q = from e in Edge, where: e.from_race_id == ^from_id and e.to_race_id == ^to_id, select: fragment("stddev(difference)") #e.difference
    Repo.one(q)
  end

end

lib/rankings_web/controllers/edge_controller.ex
defmodule RankingsWeb.EdgeController do
  use RankingsWeb, :controller

  alias Rankings.{Edge, Runner, RaceInstance, Race, Repo}

  def index(conn, _params) do
    edges = Edge.slowest_n_edges(100)
    fast_edges = Edge.fastest_n_edges(100)
    render(conn, "index.html", edges: edges, fast_edges: fast_edges)
  end

  def show(conn, %{"id" => id}) do
    edge = Edge.get_edge(id)
    sim_edges = Edge.get_edges(edge.from_race_id, edge.to_race_id)
    count = Edge.count_edges(edge.from_race_id, edge.to_race_id)
    avg = Edge.get_avg(edge.from_race_id, edge.to_race_id)
    render(conn, "show.html", edge: edge, sim_edges: sim_edges, count: count, avg: avg)
  end
end

lib/rankings_web/views/edge_view.ex
defmodule RankingsWeb.EdgeView do
  use RankingsWeb, :view
end

lib/rankings_web/templates/edge/index.html.eex
<h1>Listing Edges</h1>

<section>
<div>
<table class="main-page-top-25">
  <tr>
    <td>Runner</td>
    <td>From Race</td>
    <td>To Race</td>
    <td>Difference</td>
    <td>Edit</td>
  </tr>

  <%= for edge <- @edges do %>
    <tr>
      <td><%= link edge.runner.first_name <> " " <> edge.runner.last_name, to: Routes.runner_path(@conn, :show, edge.runner_id) %></td>
      <td><%= edge.from_race_id %></td>
      <td><%= edge.to_race_id %></td>
      <td><%= edge.difference %></td>
      <td><%= link edge.id, to: Routes.edge_path(@conn, :show, edge.id) %>
    </tr>
  <% end %>
</table>
<table class="gap-table">
</table>
<table class="main-page-top-25">
  <tr>
    <td>Runner</td>
    <td>From Race</td>
    <td>To Race</td>
    <td>Difference</td>
    <td>Edit</td>
  </tr>

  <%= for edge <- @fast_edges do %>
    <tr>
      <td><%= link edge.runner.first_name <> " " <> edge.runner.last_name, to: Routes.runner_path(@conn, :show, edge.runner_id) %></td>
      <td><%= edge.from_race_id %></td>
      <td><%= edge.to_race_id %></td>
      <td><%= edge.difference %></td>
      <td><%= link edge.id, to: Routes.edge_path(@conn, :show, edge.id) %>
    </tr>
  <% end %>
</table>
</div>
</section>

lib/rankings_web/templates/edge/show.html.eex
<h2>Edit Edge</h2>

<table>
  <tr>
    <td>Runner</td>
    <td>From Race Name</td>
    <td>To Race Name</td>
    <td>Difference</td>
    <td>Count</td>
    <td>Average</td>
  </tr>
  <tr>
    <td><%= link @edge.runner.first_name <> " " <> @edge.runner.last_name, to: Routes.runner_path(@conn, :show, @edge.runner_id) %></td>
    <td><%= link @edge.from_race.race.name, to: Routes.race_path(@conn, :show, @edge.from_race_id) %></td>
    <td><%= link @edge.to_race.race.name, to: Routes.race_path(@conn, :show, @edge.to_race_id) %></td>
    <td><%= @edge.difference %></td>
    <td><%= @count %></td>
    <td><%= @avg %></td>
    <td><%= @edge.from_race_id %></td>
    <td><%= @edge.to_race_id %></td>
  </tr>
  <div></div>
  <%= for edge <- @sim_edges do %>
    <tr>
      <td><%= edge.runner.first_name <> " " <> edge.runner.last_name%></td>
      <td><%= edge.from_race.race.name %></td>
      <td><%= edge.to_race.race.name %></td>
      <td><%= edge.difference %></td>
    </tr>
  <% end %>

</table>